# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
import os
import grading_pb2 as grading__pb2

class GraderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Grade = channel.unary_unary(
                '/grading.Grader/Grade',
                request_serializer=grading__pb2.Task.SerializeToString,
                response_deserializer=grading__pb2.Response.FromString,
                )
        self.Submit = channel.unary_unary(
                '/grading.Grader/Submit',
                request_serializer=grading__pb2.Empty.SerializeToString,
                response_deserializer=grading__pb2.Response.FromString,
                )
        self.Release = channel.unary_unary(
                '/grading.Grader/Release',
                request_serializer=grading__pb2.Task.SerializeToString,
                response_deserializer=grading__pb2.Response.FromString,
                )


class GraderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Grade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Grade': grpc.unary_unary_rpc_method_handler(
                    servicer.Grade,
                    request_deserializer=grading__pb2.Task.FromString,
                    response_serializer=grading__pb2.Response.SerializeToString,
            ),
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=grading__pb2.Empty.FromString,
                    response_serializer=grading__pb2.Response.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=grading__pb2.Task.FromString,
                    response_serializer=grading__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grading.Grader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Grader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Grade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grading.Grader/Grade',
            grading__pb2.Task.SerializeToString,
            grading__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grading.Grader/Submit',
            grading__pb2.Empty.SerializeToString,
            grading__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grading.Grader/Release',
            grading__pb2.Task.SerializeToString,
            grading__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
