# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grading.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrading.proto\x12\x07grading\"\x07\n\x05\x45mpty\"\x14\n\x04Task\x12\x0c\n\x04task\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2\x93\x01\n\x06Grader\x12+\n\x05Grade\x12\r.grading.Task\x1a\x11.grading.Response\"\x00\x12-\n\x06Submit\x12\x0e.grading.Empty\x1a\x11.grading.Response\"\x00\x12-\n\x07Release\x12\r.grading.Task\x1a\x11.grading.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grading_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=26
  _EMPTY._serialized_end=33
  _TASK._serialized_start=35
  _TASK._serialized_end=55
  _RESPONSE._serialized_start=57
  _RESPONSE._serialized_end=85
  _GRADER._serialized_start=88
  _GRADER._serialized_end=235
# @@protoc_insertion_point(module_scope)
