# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: success.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsuccess.proto\x12\x07success\"\x07\n\x05\x45mpty\"*\n\x04Task\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x14\n\x0csession_name\x18\x02 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t26\n\x05Proxy\x12-\n\x07Success\x12\r.success.Task\x1a\x11.success.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'success_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=26
  _EMPTY._serialized_end=33
  _TASK._serialized_start=35
  _TASK._serialized_end=77
  _RESPONSE._serialized_start=79
  _RESPONSE._serialized_end=107
  _PROXY._serialized_start=109
  _PROXY._serialized_end=163
# @@protoc_insertion_point(module_scope)
