# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import success_pb2 as success__pb2


class ProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Success = channel.unary_unary(
                '/success.Proxy/Success',
                request_serializer=success__pb2.Task.SerializeToString,
                response_deserializer=success__pb2.Response.FromString,
                )


class ProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Success(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Success': grpc.unary_unary_rpc_method_handler(
                    servicer.Success,
                    request_deserializer=success__pb2.Task.FromString,
                    response_serializer=success__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'success.Proxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Proxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Success(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/success.Proxy/Success',
            success__pb2.Task.SerializeToString,
            success__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
